name: Setup macOS system packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: |
          R package to test.
        default: tiff

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest }
          - { os: macos-15-intel }

    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-r-sysreqs
      - uses: r-lib/actions/setup-r@v2
      - name: Compiling R package
        run: |
          R -e 'options(warn = 2); install.packages("${{ github.event.inputs.package }}", repos = "https://cran.rstudio.com", type = "source")'
        shell: bash
